ALTER TABLE "card_page_backgrounds"
  ADD COLUMN "crop_x" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "crop_y" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "crop_scale" DOUBLE PRECISION NOT NULL DEFAULT 1;

ALTER TABLE "card_page_default_backgrounds"
  ADD COLUMN "crop_x" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "crop_y" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "crop_scale" DOUBLE PRECISION NOT NULL DEFAULT 1;
